# Generated by Django 5.2.17 on 2026-09-29 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offsetsubmission',
            name='claim_limit_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offsetsubmission',
            name='claimed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='offsetsubmission',
            name='reclaim_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DeskSetting',
            fields=[
                ('id', models.SmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('hold_limit_seconds', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '复核台设置',
            },
        ),
        migrations.CreateModel(
            name='ReclaimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_code', models.CharField(max_length=32)),
                ('claimed_at', models.DateTimeField()),
                ('limit_seconds', models.PositiveIntegerField()),
                ('held_seconds', models.FloatField()),
                ('reclaimed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclaims', to='desk.offsetsubmission')),
            ],
            options={
                'ordering': ['-reclaimed_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('submission', 'claimed_at'), name='uniq_reclaim_per_hold')],
            },
        ),
    ]
